time:
  zone: Asia/Bangkok

api:
  prefix: /api/v1

database:
  name: inventory_receipts
  host: localhost
  port: 3306
  username: root
  password: Str0ngPa5sVVord@

token:
  type: Bearer
  expiration: 2592000 #30 days
  secretKey: a5RsQm2rhY3GMgD51qK3E+aYPoe5IsnfYD0QFydCoQ0=
  expiration-refresh-token: 5184000 #60 days

swagger:
  service:
    title: API Document
    version: 1.0
    api-docs: clb.prd03.dev
    server: localhost:8080